version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_group_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend

  # PHP Service
  php:
    image: php:8.2-fpm
    container_name: php-container
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - backend
    depends_on:
      - mysql
    command: php-fpm
    build:
      context: .
      dockerfile: Dockerfile

  # Nginx for serving API requests
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - php

networks:
  backend:
    driver: bridge
